// app/components/styles/buttonStyles.js
// Common button styles for friend request features

export const friendButtonStyles = {
    send: {
        backgroundColor: '#5b21b6',
        color: 'white',
        padding: '12px 20px',
        margin: '15px 0',
        border: 'none',
        borderRadius: '8px',
        fontWeight: 'bold',
        fontSize: '16px',
        cursor: 'pointer',
        outline: 'none',
        boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
        transition: 'all 0.3s ease',
        position: 'relative',
        zIndex: 20,
        display: 'block',
        width: '100%',
        maxWidth: '200px'
    },
    sent: {
        backgroundColor: '#e11d48',
        color: 'white',
        padding: '12px 20px',
        margin: '15px 0',
        border: 'none',
        borderRadius: '8px',
        fontWeight: 'bold',
        fontSize: '16px',
        cursor: 'pointer',
        outline: 'none',
        boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
        transition: 'all 0.3s ease',
        position: 'relative',
        zIndex: 20,
        display: 'block',
        width: '100%',
        maxWidth: '200px'
    },
    accept: {
        backgroundColor: '#059669',
        color: 'white',
        padding: '12px 20px',
        margin: '15px 0',
        border: 'none',
        borderRadius: '8px',
        fontWeight: 'bold',
        fontSize: '16px',
        cursor: 'pointer',
        outline: 'none',
        boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
        transition: 'all 0.3s ease',
        position: 'relative',
        zIndex: 20,
        display: 'block',
        width: '100%',
        maxWidth: '200px'
    },
    friends: {
        backgroundColor: '#9ca3af',
        color: 'white',
        padding: '12px 20px',
        margin: '15px 0',
        border: 'none',
        borderRadius: '8px',
        fontWeight: 'bold',
        fontSize: '16px',
        cursor: 'default',
        outline: 'none',
        opacity: 0.8,
        position: 'relative',
        zIndex: 20,
        display: 'block',
        width: '100%',
        maxWidth: '200px'
    },
    loading: {
        backgroundColor: '#9ca3af',
        color: 'white',
        padding: '12px 20px',
        margin: '15px 0',
        border: 'none',
        borderRadius: '8px',
        fontWeight: 'bold',
        fontSize: '16px',
        cursor: 'wait',
        outline: 'none',
        opacity: 0.7,
        position: 'relative',
        zIndex: 20,
        display: 'block',
        width: '100%',
        maxWidth: '200px'
    }
}; 